### ISSUE TITLE
Derived measures not being generated

### ISSUE THREAD

**Issue by seven-dev** [rognerud/dbt2looker-bigquery#30]
I have a measure that is based on 2 others in the same model and it is not being generated into LookML. (@rognerud )
The code change below fixed the issue, but I understand it's not the optimal way to do it:

```
    def lookml_measures_from_model(
        self, model: DbtModel, column_list: list[DbtModelColumn], is_main_view: bool, view: dict = None
    ) -> list:
        """Generate measures from model."""
        lookml_measures = []

        for column in column_list:
            if (
                hasattr(column.meta, "looker")
                and hasattr(column.meta.looker, "measures")
                and column.meta.looker.measures
            ):
                lookml_measures.extend(
                    measure
                    for measure in (
                        self._lookml_measure(column, measure, is_main_view, view)
                        for measure in column.meta.looker.measures
                    )
                    if measure is not None
                )

        if (
            hasattr(model.meta, "looker")
            and hasattr(model.meta.looker, "measures")
            and model.meta.looker.measures
        ):
            lookml_measures.extend(
                {
                    'name': measure.name,
                    'type': measure.type.value,
                    'sql': measure.sql,
                    'description': measure.description,
                    'label': measure.label,
                }
                for measure in model.meta.looker.measures
            )

        return lookml_measures
```

**Comment by rognerud** [comment]
HI @seven-dev  do you mind sharing the yml or a similar yml so i can better understand your intent?

**Comment by rognerud** [comment]
I like this idea

**Comment by seven-dev** [comment]
For example, let's say I have 2 columns with one measure each and I want to calculate something based on those measures (this is possible in Looker). (Like an overall model measure, not specific to any column)  
So I create it on the model config and calculate something with them using SQL.  
That's what I understood a derived measure was, maybe I misunderstood... 
But yeah, the code I wrote above seemed to work for my use case, there were a few problems though:

I had to reference the measure generated names directly: `m_sum_measure1` instead of `measure1`, and also I didn't use any pydantic model, just a raw dict...  

Let me know if you have any questions.

```
version: 2

models:
  - name: some_model
    description: "Some model"
    config:
      meta:
        looker:
          view:
            label: Some model
          measures:
            - type: number
              label: "Divide 2 measures"
              name: divide_2_measures
              description: "Divide 2 measures"
              sql: ${measure1} / NULLIF(${measure2}, 0)
    columns: ...
         measure1...
         measure2...

```
